### ISSUE TITLE
zadacha3.rb and zadacha4.rb are interchanged

### ISSUE THREAD

**Issue by rakvium** [abapolov/sloboda#3]
Expected:
```
$ ruby zadacha3.rb
6857
$ ruby zadacha4.rb
906609
```

Actual:
```
$ ruby zadacha3.rb
906609
$ ruby zadacha4.rb
6857
```

You can just rename the files, yeah.

**Comment by abapolov** [comment]
@rakvium renamed :)

**Comment by rakvium** [comment]
Done in commits: 7d67a7498341af6a36639cd63ab6697b30fb60a8, 8338989811823584fc6adf6c3b628a9c322f1a96 and b1967e4d20c8551175457ec3ee9b55c48d29caca :sweat_smile:
